import { emojiData } from '../interfaces/emojies.interface';

export const Emojies: emojiData[] = [
  { emoji: '😂' },
  { emoji: '😀' },
  { emoji: '😍' },
  { emoji: '😎' },
  { emoji: '😭' },
  { emoji: '🤔' },
  { emoji: '❤️' },
  { emoji: '👍' },
  { emoji: '👏' },
  { emoji: '🎉' },
  { emoji: '🍕' },
  { emoji: '🐶' },
  { emoji: '📱' },
  { emoji: '🔥' },
  { emoji: '💯' },
  { emoji: '🤯' },
  { emoji: '🥳' },
  { emoji: '🌟' },
  { emoji: '👍' },
  { emoji: '👎' },
  { emoji: '👌' },
  { emoji: '🤌' },
  { emoji: '👏' },
  { emoji: '🙌' },
  { emoji: '🙏' },
  { emoji: '🤝' },
  { emoji: '✌️' },
  { emoji: '🤟' },
];
